### ISSUE TITLE
Readme: Add seo-friendly hide

### ISSUE THREAD

**Issue by mhulse** [mhulse/jquery-kerplop#17]
``` css
.off {
    border: 0;
    clip: rect(0 0 0 0);
    height: 1px;
    margin: -1px;
    overflow: hidden;
    padding: 0;
    position: absolute;
    width: 1px;
}
```
